" solarized theme
"set background=dark
"let g:solarized_termcolors=256
"colorscheme solarized

" onedark theme
let g:onedark_termcolors=256
let g:lightline = { 'colorscheme': 'onedark' }
colorscheme onedark

" Custom options
filetype plugin on
syntax enable
set number
set tabstop=4
set expandtab
set shiftwidth=4
set softtabstop=4
set smartindent
set autoindent
set mouse=r
set hlsearch
set ignorecase
set smartcase
set encoding=utf-8
set wildmenu
set cursorline

" Mapping F6 key for spell check
map <silent> <F6> "<Esc>:silent setlocal spell! spelllang=fr<CR>"

" fzf plugin
set rtp+=/usr/bin/fzf

" status line plugin (lightline)
set laststatus=2

" mapping key for nerdtree
map <C-o> :NERDTreeToggle<CR>
