" Custom options
color simple-dark
filetype plugin on
syntax enable
set number
set tabstop=4
set expandtab
set shiftwidth=4
set smartindent
set autoindent
set mouse=r
set hlsearch
set ignorecase
set smartcase
set encoding=utf-8
set wildmenu

" Mapping F6 key for spell check
map <silent> <F6> "<Esc>:silent setlocal spell! spelllang=fr<CR>"

